#:kivy 2.0.0
<AnimationFloatLayout>:
    FloatLayout:
        orientation: "vertical"
        size: root.width, root.height

        padding: 50
        spacing: 20


        Label:
            id: myLabel
            text: "Hello World!"
            font_size: 32
        
        Button:
            text: "Press Me!"
            font_size: 32
            size_hint: .5, .5
            pos_hint: {"center_x": .5}

            on_release: root.animate_it(self)